# Первая задача с библиотекой валидации
add_executable(lesson3_task1
        1-task.c
        input_validation.c
)

# Вторая задача без дополнительной библиотеки
add_executable(lesson3_task2
        2-task.c
)

# Третья задача без дополнительной библиотеки
add_executable(lesson3_task3
        3-task.c
)

# Четвёртая задача без дополнительной библиотеки
add_executable(lesson3_task4
        4-task.c)

# Пятая задача без дополнительной библиотеки
add_executable(lesson3_task5
        5-task.c)
