add_executable(lesson-5_task-1 1-task.c)
add_executable(lesson-5_task-2 2-task.c)
add_executable(lesson-5_task-3 3-task.c)
add_executable(lesson-5_task-4 4-task.c)
add_executable(lesson-5_task-5 5-task.c)
add_executable(lesson-5_task-6 6-task.c)
add_executable(lesson-5_task-7 7-task.c)
add_executable(lesson-5_task-8 8-task.c)
add_executable(lesson-5_task-9 9-task.c)
add_executable(lesson-5_task-10 10-task.c)
add_executable(lesson-5_task-11 11-task.c)
add_executable(lesson-5_task-12 12-task.c)
add_executable(lesson-5_task-13 13-task.c)
add_executable(lesson-5_task-14 14-task.c)
add_executable(lesson-5_task-15 15-task.c)
add_executable(lesson-5_task-16 16-task.c)
add_executable(lesson-5_task-17 17-task.c)
add_executable(lesson-5_task-18 18-task.c)
add_executable(lesson-5_task-19 19-task.c)
add_executable(lesson-5_task-20 20-task.c)
add_executable(lesson-5_task-21 21-task.c)