add_executable(lesson-4_task-1 1-task.c)
add_executable(lesson-4_task-2 2-task.c)
add_executable(lesson-4_task-3 3-task.c)
add_executable(lesson-4_task-4 4-task.c)
add_executable(lesson-4_task-5 5-task.c)
add_executable(lesson-4_task-6 6-task.c)
add_executable(lesson-4_task-7 7-task.c)
add_executable(lesson-4_task-8 8-task.c)
add_executable(lesson-4_task-9 9-task.c)
add_executable(lesson-4_task-10 10-task.c)
add_executable(lesson-4_task-11 11-task.c)
add_executable(lesson-4_task-12 12-task.c)